id: parallel_region_search
name: Parallel Regional Search
description: "Search multiple regions simultaneously"
type: parallel
nodes:
  - id: search_us
    agent_ref: comprehensive_researcher
    task: "Search US region for ${parameters.topic}"
  
  - id: search_uk
    agent_ref: comprehensive_researcher
    task: "Search UK region for ${parameters.topic}"
version: v1
