id: wf1
name: wf1
description: ''
type: sequence
nodes:
- id: node_1762443958741
  agent_ref: researcher-agent
  task: Enter task description...
  receives_from: []
  sends_to: []
- id: node_1762443965523
  agent_ref: researcher-agent
  task: Enter task description...
  receives_from: []
  sends_to: []
- id: node_1762443969130
  agent_ref: researcher-agent
  task: Enter task description...
  receives_from: []
  sends_to: []
- id: node_1762443989500
  agent_ref: researcher-agent
  task: Enter task description...
  receives_from: []
  sends_to: []
version: v1
