id: baha
name: sol
description: ''
workflows:
- ai-research-workflow
- multi_source_research
workflow_memory: {}
communication_config: {}
metadata: {}
created_at: '2025-11-07T16:20:19.593844'
updated_at: '2025-11-07T16:20:19.593844'
version: v1
