id: metrics_test_solution
name: Metrics Test Solution
description: Solution for testing metrics display
workflows:
- retest
workflow_memory: {}
communication_config: {}
metadata: {}
created_at: '2025-11-09T17:06:10.046539'
updated_at: '2025-11-09T17:06:10.046539'
version: v1
