id: web_search_general
name: General Web Search
type: websearch
config:
  engine: duckduckgo
  max_results: 5
  region: wt-wt
  safesearch: moderate
  timelimit: null
description: "General purpose web search using DuckDuckGo"
version: v1
